from datetime import UTC, date, datetime, timedelta, timezone
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import DefaultClause, create_engine, inspect, text
from sqlalchemy.exc import IntegrityError, StatementError

from app.config import Settings
from app.db.session import configure_database, get_db_session
from app.db.models import (
    DailyUsage,
    EventLevel,
    ProcessingStyle,
    Task,
    TaskEvent,
    TaskStatus,
    TaskType,
    Upload,
    UploadStatus,
)


def test_upload_and_task_defaults(db_session) -> None:
    upload = Upload(
        id="upload-1",
        client_id_hash="client",
        ip_hash="ip",
        original_file_name="m31.fits",
        stored_path="/tmp/input.fits",
        size_bytes=128,
        status=UploadStatus.READY,
        expires_at=datetime.now(UTC) + timedelta(hours=1),
    )
    task = Task(
        id="task-1",
        type=TaskType.ANALYSIS,
        status=TaskStatus.QUEUED,
        client_id_hash="client",
        ip_hash="ip",
        upload_id=upload.id,
    )
    db_session.add_all([upload, task])
    db_session.commit()
    db_session.refresh(task)

    assert task.progress == 0
    assert task.retryable is False
    assert task.quota_charged is False
    assert task.free_retry_used is False


def test_task_event_sequence_is_unique_per_task(db_session) -> None:
    task = Task(
        id="task-events",
        type=TaskType.ANALYSIS,
        status=TaskStatus.QUEUED,
        client_id_hash="client",
        ip_hash="ip",
    )
    task.events.extend(
        [
            TaskEvent(
                sequence=1,
                level=EventLevel.INFO,
                event_type="queued",
                payload={"position": 1},
            ),
            TaskEvent(
                sequence=1,
                level=EventLevel.WARNING,
                event_type="duplicate",
            ),
        ]
    )
    db_session.add(task)

    with pytest.raises(IntegrityError):
        db_session.commit()


def test_daily_usage_key_is_unique(db_session) -> None:
    usage_date = date(2026, 6, 11)
    db_session.add(
        DailyUsage(
            date=usage_date,
            client_id_hash="client",
            ip_hash="ip",
        )
    )
    db_session.commit()

    usage = db_session.query(DailyUsage).one()
    assert usage.count == 0

    db_session.add(
        DailyUsage(
            date=usage_date,
            client_id_hash="client",
            ip_hash="ip",
        )
    )
    with pytest.raises(IntegrityError):
        db_session.commit()


def test_sqlite_foreign_keys_are_enforced(db_session) -> None:
    db_session.add(
        Task(
            id="task-missing-upload",
            type=TaskType.ANALYSIS,
            status=TaskStatus.QUEUED,
            client_id_hash="client",
            ip_hash="ip",
            upload_id="missing-upload",
        )
    )

    with pytest.raises(IntegrityError):
        db_session.commit()


def test_settings_defaults(monkeypatch) -> None:
    for setting_name in Settings.model_fields:
        monkeypatch.delenv(f"STARUN_{setting_name.upper()}", raising=False)

    settings = Settings(_env_file=None)

    assert settings.database_url == "sqlite:///./starun.db"
    assert settings.data_root == Path("./data")
    assert settings.max_upload_bytes == 500 * 1024 * 1024
    assert settings.upload_ttl_seconds == 3600
    assert settings.task_ttl_seconds == 86400
    assert settings.daily_task_limit == 5
    assert settings.analysis_timeout_seconds == 600
    assert settings.processing_timeout_seconds == 3600
    assert settings.min_free_disk_bytes == 5 * 1024 * 1024 * 1024


def test_settings_use_starun_environment_prefix(monkeypatch, tmp_path) -> None:

    database_url = f"sqlite:///{tmp_path / 'settings.db'}"
    data_root = tmp_path / "data"
    monkeypatch.setenv("STARUN_DATABASE_URL", database_url)
    monkeypatch.setenv("STARUN_DATA_ROOT", str(data_root))
    monkeypatch.setenv("STARUN_DAILY_TASK_LIMIT", "9")

    settings = Settings()

    assert settings.database_url == database_url
    assert settings.data_root == data_root
    assert settings.daily_task_limit == 9


def test_enum_values_persist_as_lowercase_contract_strings(db_session) -> None:
    upload = Upload(
        id="upload-enums",
        client_id_hash="client",
        ip_hash="ip",
        original_file_name="m42.fits",
        stored_path="/tmp/m42.fits",
        size_bytes=256,
        status=UploadStatus.VALIDATING,
        expires_at=datetime.now(UTC) + timedelta(hours=1),
    )
    task = Task(
        id="task-enums",
        type=TaskType.PROCESSING,
        status=TaskStatus.RUNNING,
        style=ProcessingStyle.ARTISTIC,
        client_id_hash="client",
        ip_hash="ip",
        upload=upload,
    )
    task.events.append(
        TaskEvent(
            sequence=1,
            level=EventLevel.ERROR,
            event_type="failed",
        )
    )
    db_session.add(task)
    db_session.commit()

    assert db_session.execute(
        text("SELECT status FROM uploads WHERE id = 'upload-enums'")
    ).scalar_one() == "validating"
    assert db_session.execute(
        text("SELECT type || ':' || status || ':' || style FROM tasks WHERE id = 'task-enums'")
    ).scalar_one() == "processing:running:artistic"
    assert db_session.execute(
        text("SELECT level FROM task_events WHERE task_id = 'task-enums'")
    ).scalar_one() == "error"
    assert task.events[0].payload == {}


def test_datetime_values_round_trip_as_aware_utc(db_session) -> None:
    now = datetime.now(UTC)
    offset_time = now.astimezone(timezone(timedelta(hours=8)))
    upload = Upload(
        id="upload-datetime",
        client_id_hash="client",
        ip_hash="ip",
        original_file_name="m51.fits",
        stored_path="/tmp/m51.fits",
        size_bytes=512,
        status=UploadStatus.READY,
        created_at=offset_time,
        expires_at=offset_time + timedelta(hours=1),
        claimed_at=offset_time + timedelta(minutes=1),
    )
    task = Task(
        id="task-datetime",
        type=TaskType.ANALYSIS,
        status=TaskStatus.RUNNING,
        client_id_hash="client",
        ip_hash="ip",
        upload=upload,
        cancel_requested_at=offset_time + timedelta(minutes=2),
        delete_requested_at=offset_time + timedelta(minutes=2),
        cleanup_pending=True,
        cleanup_error="diagnostic_id=cleanup-test",
        cleanup_plan={"task_dir": True, "source_path": True},
        created_at=offset_time,
        started_at=offset_time + timedelta(minutes=3),
        finished_at=offset_time + timedelta(minutes=4),
        expires_at=offset_time + timedelta(hours=2),
    )
    task.events.append(
        TaskEvent(
            sequence=1,
            level=EventLevel.INFO,
            event_type="started",
            created_at=offset_time + timedelta(minutes=3),
        )
    )
    db_session.add(task)
    db_session.commit()
    db_session.expire_all()

    reloaded = db_session.get(Task, task.id)
    assert reloaded is not None
    assert reloaded.created_at.tzinfo is UTC
    assert reloaded.created_at == now
    assert reloaded.delete_requested_at == offset_time + timedelta(minutes=2)
    assert reloaded.cleanup_pending is True
    assert reloaded.cleanup_error == "diagnostic_id=cleanup-test"
    assert reloaded.cleanup_plan == {"task_dir": True, "source_path": True}
    stored_created_at = db_session.execute(
        text("SELECT created_at FROM tasks WHERE id = 'task-datetime'")
    ).scalar_one()
    assert datetime.fromisoformat(stored_created_at) == now.replace(tzinfo=None)
    assert reloaded.upload is not None
    assert reloaded.upload.expires_at.tzinfo is UTC
    assert reloaded.events[0].created_at.tzinfo is UTC


def test_naive_datetime_is_rejected(db_session) -> None:
    db_session.add(
        Upload(
            id="upload-naive",
            client_id_hash="client",
            ip_hash="ip",
            original_file_name="naive.fits",
            stored_path="/tmp/naive.fits",
            size_bytes=64,
            status=UploadStatus.READY,
            expires_at=datetime.now(),
        )
    )

    with pytest.raises(StatementError, match="UTC-aware"):
        db_session.commit()


@pytest.mark.parametrize(
    ("statement", "parameters"),
    [
        (
            """
            INSERT INTO uploads (
                id, client_id_hash, ip_hash, original_file_name, stored_path,
                size_bytes, status, created_at, expires_at
            ) VALUES (
                :id, 'client', 'ip', 'invalid.fits', '/tmp/invalid.fits',
                1, 'bogus', :now, :expires_at
            )
            """,
            {"id": "upload-invalid-status"},
        ),
        (
            """
            INSERT INTO tasks (
                id, type, status, client_id_hash, ip_hash, created_at
            ) VALUES (
                :id, 'bogus', 'queued', 'client', 'ip', :now
            )
            """,
            {"id": "task-invalid-type"},
        ),
        (
            """
            INSERT INTO tasks (
                id, type, status, client_id_hash, ip_hash, created_at
            ) VALUES (
                :id, 'analysis', 'bogus', 'client', 'ip', :now
            )
            """,
            {"id": "task-invalid-status"},
        ),
        (
            """
            INSERT INTO tasks (
                id, type, status, style, client_id_hash, ip_hash, created_at
            ) VALUES (
                :id, 'processing', 'queued', 'bogus', 'client', 'ip', :now
            )
            """,
            {"id": "task-invalid-style"},
        ),
        (
            """
            INSERT INTO task_events (
                task_id, sequence, level, event_type, created_at
            ) VALUES (
                'task-valid-for-event', 1, 'bogus', 'invalid', :now
            )
            """,
            {},
        ),
    ],
)
def test_sqlite_enum_constraints_reject_invalid_raw_values(
    db_session,
    statement,
    parameters,
) -> None:
    now = datetime.now(UTC)
    db_session.add(
        Task(
            id="task-valid-for-event",
            type=TaskType.ANALYSIS,
            status=TaskStatus.QUEUED,
            client_id_hash="client",
            ip_hash="ip",
        )
    )
    db_session.commit()

    with pytest.raises(IntegrityError):
        db_session.execute(
            text(statement),
            parameters
            | {
                "now": now.replace(tzinfo=None).isoformat(),
                "expires_at": (now + timedelta(hours=1)).replace(tzinfo=None).isoformat(),
            },
        )


def test_application_session_dependency_reuses_configured_engine(tmp_path) -> None:
    engine = configure_database(f"sqlite:///{tmp_path / 'application.db'}")
    first_dependency = get_db_session()
    second_dependency = get_db_session()
    first_session = next(first_dependency)
    second_session = next(second_dependency)
    try:
        assert first_session.bind is engine
        assert second_session.bind is engine
    finally:
        first_dependency.close()
        second_dependency.close()
        configure_database(Settings().database_url)


def test_initial_migration_creates_expected_tables(monkeypatch, tmp_path) -> None:
    api_root = Path(__file__).resolve().parents[2]
    database_url = f"sqlite:///{tmp_path / 'migration.db'}"
    monkeypatch.setenv("STARUN_DATABASE_URL", database_url)

    alembic_config = Config(api_root / "alembic.ini")
    command.upgrade(alembic_config, "head")

    engine = create_engine(database_url)
    try:
        inspector = inspect(engine)
        assert {
            "alembic_version",
            "daily_usage",
            "task_events",
            "tasks",
            "uploads",
        } == set(inspector.get_table_names())
        assert {index["name"] for index in inspector.get_indexes("uploads")} == {
            "ix_uploads_status_expires_at"
        }
        assert {index["name"] for index in inspector.get_indexes("tasks")} == {
            "ix_tasks_expires_at",
            "ix_tasks_status_created_at",
        }
        assert inspector.get_indexes("task_events") == []
        assert {
            constraint["name"]
            for constraint in inspector.get_check_constraints("uploads")
        } == {"uploadstatus_enum"}
        assert {
            constraint["name"]
            for constraint in inspector.get_check_constraints("tasks")
        } == {
            "processingstyle_enum",
            "taskstatus_enum",
            "tasktype_enum",
        }
        assert {
            constraint["name"]
            for constraint in inspector.get_check_constraints("task_events")
        } == {"eventlevel_enum"}
        assert {
            constraint["name"]
            for constraint in inspector.get_unique_constraints("task_events")
        } == {"uq_task_event_sequence"}
        assert {
            constraint["name"]
            for constraint in inspector.get_unique_constraints("daily_usage")
        } == {"uq_daily_usage_client"}
        assert {
            foreign_key["referred_table"]
            for foreign_key in inspector.get_foreign_keys("tasks")
        } == {
            "tasks",
            "uploads",
        }
        event_foreign_key = inspector.get_foreign_keys("task_events")[0]
        assert event_foreign_key["referred_table"] == "tasks"
        assert event_foreign_key["options"] == {"ondelete": "CASCADE"}
    finally:
        engine.dispose()


def test_alembic_detects_server_default_drift(monkeypatch, tmp_path) -> None:
    api_root = Path(__file__).resolve().parents[2]
    database_url = f"sqlite:///{tmp_path / 'drift.db'}"
    monkeypatch.setenv("STARUN_DATABASE_URL", database_url)
    alembic_config = Config(api_root / "alembic.ini")
    command.upgrade(alembic_config, "head")
    command.check(alembic_config)

    progress_column = Task.__table__.c.progress
    original_default = progress_column.server_default
    progress_column.server_default = DefaultClause(text("99"))
    try:
        with pytest.raises(AutogenerateDiffsDetected):
            command.check(alembic_config)
    finally:
        progress_column.server_default = original_default


def test_test_fixtures_are_isolated(settings, data_root, headers, client) -> None:
    assert settings.database_url.endswith("/test.db")
    assert settings.data_root == data_root
    assert data_root.is_dir()
    assert headers == {"X-Starun-Client-Id": "test-client"}
    assert client.get("/api/health", headers=headers).json() == {"status": "ok"}
